# Generated by Django 6.0 on 2026-01-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_creditcard_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='friends',
            field=models.ManyToManyField(blank=True, to='customers.customer'),
        ),
    ]
